version: 2

sources:
    - name: staging
      database: data-engineering-362120
      schema: trips_data_all

      tables:
        - name: external_yellow_partitioned
        - name: external_green_partitioned